DROP TABLE IF EXISTS TAG;
DROP TABLE IF EXISTS NODE;

CREATE TABLE NODE
(
    ID        BIGINT PRIMARY KEY,
    USER_NAME VARCHAR(255)     NOT NULL,
    LONGITUDE DOUBLE PRECISION NOT NULL,
    LATITUDE  DOUBLE PRECISION NOT NULL
);

CREATE TABLE TAG
(
    ID    SERIAL PRIMARY KEY,
    NODE  BIGINT       NOT NULL,
    KEY   VARCHAR(255) NOT NULL,
    VALUE VARCHAR(255) NOT NULL
);
